version: "2.6.0"

services:
    pgdb:
        # profiles: ["dev"]
        container_name: pgdb_ecommerce
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    esearch:
        container_name: search
        image: elasticsearch:7.14.2
        environment:
            - cluster.name=ecommerce-elasticsearch
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - ES_JAVA_OPTS=-Xms128m -Xmx128m
        ports:
            - "9200:9200"
        volumes:
            - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        depends_on:
            - pgdb
    # pgadmin:
    #   container_name: pgadmin4
    #   image: dpage/pgadmin4
    #   restart: always

    #   environment:
    #     PGADMIN_DEFAULT_EMAIL: a@a.com
    #     PGADMIN_DEFAULT_PASSWORD: password
    #   ports:
    #     - "5050:80"
    # elasticsearch:
    #     container_name: elasticsearch_ecommercev2
    #     image: elasticsearch:7.14.2
    #     environment:
    #         # - cluster.name=ecommerce-elasticsearch
    #         - discovery.type=single-node
    #         # - bootstrap.memory_lock=true
    #         # - ES_JAVA_OPTS=-Xms128m -Xmx128m
    #     ports:
    #         - "9200:9200"
    #     volumes:
    #         - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    #     depends_on:
    #         - pgdb
